### ISSUE TITLE
Can this be ported to Node?

### ISSUE THREAD

**Issue by Swiftnesses** [NeatoRobotics/neato-sdk-js#1]
I'm looking to build an App for Homey (www.athom.com) which uses NodeJS.

Could a Node version be created? I'm hesitant to use one of the unofficial Node ports...

**Comment by ostinelli** [comment]
Indeed, this can be used as a basis for a node port. We're currently not working on it, but have asked if the author of the unofficial node module would consider using the official APIs https://github.com/Pmant/node-botvac/issues/1.

**Comment by markaswift** [comment]
I've completed by app for Homey (Home automation device).

It's amazing!

https://github.com/markaswift/nl.joolee.homey.neato

**Comment by markaswift** [comment]
BTW guys, looking forward to the Botvac Connected getting an update, I see some nice things in the API "navigationMode" etc
