### ISSUE TITLE
Start Command no longer works on the D3

### ISSUE THREAD

**Issue by koush** [NeatoRobotics/neato-sdk-js#10]
The start command on the D3 no longer works. I've updated to the latest version of the Neato firmware.

I noticed this initially in my Android application, and then confirmed the issue on the reference Javascript client.
The start command is ignored or no longer a function per the javascript console log:
```
neato-demo-app.js:76 Uncaught TypeError: this.user.getRobotBySerial(...).startHouseCleaning is not a function
    at Object.startHouseCleaning (neato-demo-app.js:76)
    at Object.startOrResume (neato-demo-app.js:69)
    at HTMLAnchorElement.<anonymous> (neato-demo-app.js:180)
    at HTMLDocument.dispatch (jquery.min.js:3)
    at HTMLDocument.r.handle (jquery.min.js:3)
```

I believe there needs to be an sdk update?

**Comment by ostinelli** [comment]
Hello,
The SDK does not contain the most recent services yet. You may use custom calls and define them according to the services as defined in:
https://developers.neatorobotics.com/api/robot-remote-protocol/housecleaning

Hope this helps.

**Comment by koush** [comment]
Thanks. Figured that out after forking the SDK and stepping through to find the failure. I created a pull request with stubbed out 3 and 4 services. I'm not sure exactly what capabilities they provide, so I just used the v2 service. This, at the very least, allows the "start" command to function again.

**Comment by koush** [comment]
https://github.com/NeatoRobotics/neato-sdk-android/pull/2
