### ISSUE TITLE
Access to robot's position/accelerometer

### ISSUE THREAD

**Issue by raRaRa** [NeatoRobotics/neato-sdk-js#2]
Hi,

Is it possible to access the robot's position or accelerometer? I own the D5 Connected and it somehow manages to navigate back to the charging base. There has to be some navigation data that I can access, correct?

It would open the doors for great apps, such as drawing the area it's been in, ability to click on a position on the map to tell the robot to spot clean, etc.

On a side note, is there any specific reason why the coverage map is not available on the D5 Connected if it has all the same navigation features and sensors?

Poking @ostinelli 

Thanks.

**Comment by ostinelli** [comment]
The cloud API do not allow to access low-level API such as accelerometers and navigation data. We are working to extend those functionalities and will keep your suggestions in mind. Thank you!

**Comment by Tukks** [comment]
Do you have any update on this?
