### ISSUE TITLE
Possibility to manually steer the Neato when nav fails or other problems occur

### ISSUE THREAD

**Issue by cajonKA** [NeatoRobotics/neato-sdk-js#6]
I have a D5 Connected and I really like your product and the possibilities the SDK gives me.
But what I really miss is the possibility to give the neato manual commands when it got stuck.
My D5 runs when I am NOT at home, so it would be great if I had some possibility (e.g. go back, turn left, turn right) when it is stuck so that it can continue its job.
Is there a plan to extend the SDK so that manual commands will be available (from the same wlan, of course)

**Comment by marcouberti** [comment]
Hi, unfortunately when the robot is stuck it's in an ERROR state and require that the user physically unlock it. So you cannot control remotely your robot when it enters an ERROR state, manually or not. 
Anyway the SDK doesn't contain the methods to connect via web sockets to the robot currently, but you can implement yourself using the [Manual Cleaning API](https://developers.neatorobotics.com/api/robot-remote-protocol/manualcleaning).

**Comment by cajonKA** [comment]
Is this possible for the D5 Connected

**Comment by marcouberti** [comment]
Oh sorry, the D5 doesn't have the manual drive feature, you're right. Only the Botvac Connected and D7 have this feature. Maybe the D5 features can be extended in the future but for now there aren't plans to do that.

**Comment by cajonKA** [comment]
This is very sad, but the normal "we only give the full feature variety to our high price product" philosophy that every tech company has.  
Thanks for your quick answer anyway.
And by the way, If NEATO would open up their bots a little more, I am very sure that they could gain a lot more customers from the home automation scene.

**Comment by ostinelli** [comment]
Thank you for your feedback.

**Comment by sharifza** [comment]
This is quite strange. I don't think D5 has any lack of physical features that would prevent it from using manual control. I really like D5 but now xiaomi roborock s5 is being offered almost at the same price and let alone its mopping and carpet detection, it offers manual control which can be easily added to D5 with an update. With manual control for example one can also compensate the lack of carpet detection and manually drive the Neato to the carpet and turn on the boosted vaccuming.
